### ISSUE TITLE
Statistics endpoints needed

### ISSUE THREAD

**Issue by jadianes** [PRIDE-Cluster/cluster-web-service#10]
The Web-Service needs end-points providing data statistics. This will be taken from the [repo Cluster results Statistics](https://github.com/PRIDE-Cluster/cluster-repo/issues/7) and among others, will be used on the webapp landing page.

**Comment by jadianes** [comment]
The shape of the data should be similar to the key-value counts we have for a cluster species.

**Comment by ruiwanguk** [comment]
All the implementation is done, a new deployment of the web service is needed.
