### ISSUE TITLE
PTM counts are needed for a Cluster

### ISSUE THREAD

**Issue by jadianes** [PRIDE-Cluster/cluster-web-service#11]
A web service end-point, following the exact same philosophy we have for [Cluster species counts](https://github.com/PRIDE-Cluster/cluster-web-service/blob/master/src/main/java/uk/ac/ebi/pride/cluster/ws/modules/cluster/controller/ClusterController.java#L125) is needed for a Cluster PTMs

**Comment by ypriverol** [comment]
@ruiwanguk @jadianes Do you know if is possible with the pom file you send me to connect to the EBI solr or the databses or do i need to have a local instance or tunneling?

**Comment by jadianes** [comment]
As far as I know DDBBs and Solr indexes are not accessible outside of the EBI... If you find out how to do all the tunneling stuff I'll be super happy to know about it :)

**Comment by ypriverol** [comment]
I try before when I was in cuba before, tunnelling the ports from the solar (mysql) machine to my local ports. I will try to configure it here. BTW how do you test this in your local machine? Can you share with me (dropbox) your solr instance.

**Comment by jadianes** [comment]
I can replicate the Solr index, but not the DDBB. For Solr I use docker:

https://registry.hub.docker.com/u/jadianes/solr-cloud-cluster/

That's a dockerized Solr instance with our PRIDE Cluster index already configured. Run it with mapped ports, etc. so you can access on your localhost.

**Comment by ypriverol** [comment]
Thanks Jose, I will used it here. The DDBB is in oracle, thats why we can not run it?

**Comment by jadianes** [comment]
It is an Oracle DDBB, yes. The schema and repo library is in GitHub. Nothing stops you from recreating the DDBB locally but the data, that as you know comes from our file system, needs to be extracted and inserted into the DDBB with the pipeline. Actually I think is easier to find a solution using VPN or tunneling than trying to replicate the DDBB...

**Comment by ypriverol** [comment]
Thanks Jose

**Comment by ruiwanguk** [comment]
Implementation is done, testing is needed

**Comment by ruiwanguk** [comment]
tested
