### ISSUE TITLE
Additional detail data needed

### ISSUE THREAD

**Issue by jadianes** [PRIDE-Cluster/cluster-web-service#12]
The following WS end-point for [Cluster summary](https://github.com/PRIDE-Cluster/cluster-web-service/blob/master/src/main/java/uk/ac/ebi/pride/cluster/ws/modules/cluster/controller/ClusterController.java#L57) needs to be expanded with the following data:  
* Number of species in the cluster  
* Number of PTMs in the cluster  
* Number of projects in the cluster  

Further details of species, PTMs, and projects, will be found in separate end-points under the cluster prefix (e.g. [Species](https://github.com/PRIDE-Cluster/cluster-web-service/blob/master/src/main/java/uk/ac/ebi/pride/cluster/ws/modules/cluster/controller/ClusterController.java#L125)) or under a separate end-point if the entity contains enough information to be accessed on its own (e.g. [PSM](https://github.com/PRIDE-Cluster/cluster-web-service/blob/master/src/main/java/uk/ac/ebi/pride/cluster/ws/modules/psm/controller/PsmController.java)) or **project** (to be done).

**Comment by ruiwanguk** [comment]
These information will be need to be provided by Solr index, right now the implementation has been done in web service, where we added these fields and also provide pesudo numbers for these fields.

**Comment by jadianes** [comment]
Fair enough. I've created a [new issue in the indexer](https://github.com/PRIDE-Cluster/cluster-indexer/issues/1) for this data to be added to the index.
