### ISSUE TITLE
project end point

### ISSUE THREAD

**Issue by jadianes** [PRIDE-Cluster/cluster-web-service#13]
A project web-service end point is needed. Since project information will go beyond simple counts, this should be part of a root-level end point and **not** just contained as a fragment of the **cluster** end point. A similar approach to that for [PSMs](https://github.com/PRIDE-Cluster/cluster-web-service/blob/master/src/main/java/uk/ac/ebi/pride/cluster/ws/modules/psm/controller/PsmController.java) should be taken.

**Comment by ruiwanguk** [comment]
Implementation is done, but needs testing

**Comment by ruiwanguk** [comment]
done
