### ISSUE TITLE
Data for confidence charts

### ISSUE THREAD

**Issue by jadianes** [PRIDE-Cluster/cluster-web-service#14]
In order to implement the [confidence charts](https://github.com/PRIDE-Cluster/cluster-design/blob/master/mockups/cluster.md#confidence-charts) as described, the WS is required to provide related data for spectra given a cluster. If we are going to have multiple data for each spectrum item I would go for a solution in a separate end-point as we have for [PSMs](https://github.com/PRIDE-Cluster/cluster-web-service/blob/master/src/main/java/uk/ac/ebi/pride/cluster/ws/modules/psm/controller/PsmController.java).

**Comment by ruiwanguk** [comment]
Web service implemented and tested
