### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by jadianes** [PRIDE-Cluster/cluster-web-service#6]
From FR:
consider more concrete/consistent names for some fields, like 'results' in cluster summary search results, or 'numberOfSpectra' and 'numSpectra' in ClusterDetail, ...

**Comment by ruiwanguk** [comment]
@jadianes Is this issue still valid?

**Comment by jadianes** [comment]
I think I solved this when unifying the model objects... Let's close it.
